# Generated by Django 5.0.4 on 2024-04-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='country',
        ),
        migrations.AddField(
            model_name='news',
            name='modified_dates',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
