# Generated by Django 4.2.7 on 2024-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_country_news_modified_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
