# Generated by Django 5.0.4 on 2024-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_country_alter_news_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
