# Generated by Django 5.0.4 on 2024-05-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_date_news_modified_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='modified_dates',
            field=models.DateField(blank=True, null=True),
        ),
    ]
