# Generated by Django 5.0.4 on 2024-04-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_tweet_tweet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='hashtags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='lang',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='reach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_friends_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_screen_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
