# Generated by Django 5.0.4 on 2024-04-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_tweet_favorite_count_tweet_hashtags_tweet_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user_followers_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
