# Generated by Django 5.0.4 on 2024-05-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_alter_tweet_user_followers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='entity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
